### PR TITLE
Adjust messages to direct people toward help

### PR DESCRIPTION
**Pull request by paulproteus**
Refs #49

### CODE REVIEW

**Comment by kentonv** [comment]
Should there be quotes around "help"?

**Comment by paulproteus** [comment]
I always wonder about that.

I lean toward no, because then people will type

`"help"`

and I don't want to adjust my code to permit that.

**Comment by kentonv** [comment]
Compromise: write it in a different color or format (e.g. bold, underlined). Has the added bonus of drawing the user's eyes to the command. :)

**Comment by paulproteus** [comment]
+0 but the install integration right now just does `cat`.

I guess it could do some hilarious ANSI colorizing. I just filed an issue
requesting that, though I plan to handle it with "wishlist" priority.

**Pull request merged**
