### PR TITLE
For rose.makesad.us, ignore one specific GlobalSign warning aka error

### PR DESCRIPTION
**Pull request by paulproteus**

### CODE REVIEW

**Comment by paulproteus** [comment]
Self-merging ahead of CI.

**Comment by ocdtrekkie** [comment]
This does make us sad. Worth asking... why is it here?

**Comment by paulproteus** [comment]
I'm debugging a globalsign API issue where they are returning an error that seems not to be an error.

**Comment by paulproteus** [comment]
First I'll whitelist rose as skipping the error, and if that works OK, then I'll skip the error for everyone, at which point I'll ask my globalsign api contact what is going on.

**Comment by ocdtrekkie** [comment]
Oh, that's sensible.

**Pull request merged**
