### PR TITLE
Disable /getcertificate

### PR DESCRIPTION
**Pull request by kentonv**
Done as a minimal hack for now.

### CODE REVIEW

**Comment by zenhack** [comment]
Any reason not to delete the rest of the function body?

**Comment by kentonv** [comment]
@zenhack No good reason, just that I'm carefully applying these patches directly to the running service so that I don't have to try to rebuild it, and I want to keep the modifications pretty minimal...

**Comment by zenhack** [comment]
Fair enough. If you weren't planning on rewriting this as a worker
anyway I'd take this as a sign that we need to do some serious cleanup,
but between that and the fact that this is time sensitive I'm OK with
shortcutting it a bit.

**Comment by kentonv** [comment]
Yeah I'm hoping to retire this whole thing...

**Pull request merged**
